### PR TITLE
Correct indentation, incorrect commenting conventions

### PR DESCRIPTION
**Pull request by camdez**
No functional changes, just bringing code in line with Emacs Lisp coding conventions on indentation, commenting, and paren placement.

### CODE REVIEW

**Comment by camdez** [comment]
Recommend looking at [the diff with whitespace changes hidden](https://github.com/Floobits/floobits-emacs/pull/77/files?w=1).

**Comment by btipling** [comment]
Did you run a program to do that? Is there a linter or something you recommend? Thanks.

**Comment by camdez** [comment]
I just used Emacs to correct the indentation—`C-x h` `C-m-\` (`mark-whole-buffer`, `indent-region`). The other little changes were manual.

For proper linting, I highly recommend [flycheck-mode](https://github.com/flycheck/flycheck), but for Elisp it will really just wrap the built-in elint commands (check out `C-h a elint RET`).

**Comment by ggreer** [comment]
Ah, thanks for the PR and the info.

**Comment by camdez** [comment]
No problem. There are a couple additional style issues I'll tackle soon but alas, day job. ;)

**Pull request merged**
