### PR TITLE
remove highlight.el

### PR DESCRIPTION
**Pull request by tarsius**
Most users probably get this package from Melpa now and that does
not include the bundled `highlight.el`, which demonstrates that
this patched version is no longer required.

Remove it so that those users who install `floobits` using git
submodules are not negatively affected by an outdated version
laying around on their `load-path`.

### CODE REVIEW

**Comment by tarsius** [comment]
Friendly ping ;-)

**Comment by tarsius** [comment]
Here's another friendly ping for you!

**Comment by ggreer** [comment]
Highlight.el doesn't ship with Emacs 24, so removing this file breaks the plugin for users without MELPA.

Sorry, but it looks like this crufty code is going to stick around for a while.

**Comment by tarsius** [comment]
> Highlight.el doesn't ship with Emacs 24, so removing this file breaks the plugin for users without MELPA.

True, those users (which includes myself) will now have to install `highlight` separately. The argument I was trying to make is that some of those users might *already* have installed it separately. When such a user updates that separately installed `highlight` s/he expects that version to be loaded. However your package bundles an older copy and so it is undefined which version gets loaded (it depends on the order of the `load-path`). This can be very confusing. Imagine you update `highlight` to get a new feature and that feature simply not being there even after recompiling and restarting Emacs...

**Comment by ggreer** [comment]
Fixed by #94.

**Pull request closed without merging**
