### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by camdez**
A few more styling tweaks. Looks far-reaching, but really not so much.

### CODE REVIEW

**Comment by ggreer** [comment]
LGTM, but there's a merge conflict?

**Comment by ggreer** [comment]
Thanks for cleaning this stuff up.

**Comment by camdez** [comment]
@ggreer Sure thing! I'm thinking of hacking on the code a bit—step one is to tidy up the workshop. ;)

**Comment by camdez** [comment]
@ggreer I added one little commit (6482c5627b7df24dc383acf1d03fdc8a61d19c4e) to master that didn't make it before you merged. Hope that's cool.

**Comment by ggreer** [comment]
Yep, that's fine.

**Pull request merged**
